project:
  type: website

website:
  favicon: profile.png
  title: "aparticularist"
  navbar:
    right:
      - about.qmd
format:
  html:
    theme: 
      - litera
    css: styles.css

mainfont: "Gothic Round B"